"use client";
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import type { AdvisoryResult, Recommendation } from "@/lib/api";

const S = StyleSheet.create({
  page:       { fontFamily: "Helvetica", padding: 40, backgroundColor: "#ffffff", fontSize: 10 },
  header:     { marginBottom: 24, paddingBottom: 14, borderBottomWidth: 2, borderBottomColor: "#111" },
  h1:         { fontSize: 26, fontFamily: "Helvetica-Bold", marginBottom: 4, letterSpacing: 1 },
  subtitle:   { fontSize: 10, color: "#666", marginBottom: 2 },
  badge:      { fontSize: 8, color: "#fff", backgroundColor: "#16a34a", padding: "3 7", borderRadius: 2 },
  sectionHdr: { fontSize: 9, fontFamily: "Helvetica-Bold", color: "#666", letterSpacing: 1.2,
                textTransform: "uppercase", marginTop: 18, marginBottom: 8, paddingBottom: 4,
                borderBottomWidth: 1, borderBottomColor: "#e5e7eb" },
  recCard:    { marginBottom: 8, padding: "10 12", borderLeftWidth: 3 },
  recText:    { fontSize: 10, fontFamily: "Helvetica-Bold", marginBottom: 3, lineHeight: 1.4 },
  basisText:  { fontSize: 9, color: "#555", lineHeight: 1.4 },
  confText:   { fontSize: 8, color: "#888", marginTop: 2 },
  statsRow:   { display: "flex", flexDirection: "row", gap: 16, marginBottom: 20, marginTop: 8 },
  statBox:    { flex: 1, padding: "8 10", backgroundColor: "#f9fafb", borderWidth: 1, borderColor: "#e5e7eb" },
  statNum:    { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 2 },
  statLabel:  { fontSize: 8, color: "#666" },
  footer:     { marginTop: 30, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#e5e7eb",
                fontSize: 8, color: "#aaa", textAlign: "center" },
});

const PRI_COLORS: Record<string, string> = {
  CRITICAL: "#ef4444", HIGH: "#f97316", MEDIUM: "#eab308", LOW: "#22c55e",
};

const PHASES = ["PRE-SEASON", "IN-SEASON", "POST-SEASON"];

interface Props { advisory: AdvisoryResult; farm: Record<string, unknown> }

function AdvisoryDocument({ advisory, farm }: Props) {
  const byPhase: Record<string, Recommendation[]> = {};
  advisory.recommendations.forEach((r) => {
    byPhase[r.phase] = [...(byPhase[r.phase] ?? []), r];
  });

  return (
    <Document title={`MA-XAI Advisory — ${advisory.farm_label}`}>
      <Page size="A4" style={S.page}>
        {/* Header */}
        <View style={S.header}>
          <Text style={S.h1}>MA-XAI Advisory Report</Text>
          <Text style={S.subtitle}>{advisory.farm_label}</Text>
          <Text style={S.subtitle}>Generated: {new Date().toLocaleDateString("en-IN", { day:"numeric", month:"long", year:"numeric" })}</Text>
        </View>

        {/* Key stats */}
        <View style={S.statsRow}>
          <View style={S.statBox}>
            <Text style={{ ...S.statNum, color: "#16a34a" }}>{advisory.predicted_yield.toFixed(1)}</Text>
            <Text style={S.statLabel}>Predicted Yield (q/ha)</Text>
          </View>
          <View style={S.statBox}>
            <Text style={{ ...S.statNum, color: "#ef4444" }}>{advisory.n_critical}</Text>
            <Text style={S.statLabel}>Critical Alerts</Text>
          </View>
          <View style={S.statBox}>
            <Text style={{ ...S.statNum, color: "#f97316" }}>{advisory.n_high}</Text>
            <Text style={S.statLabel}>High Priority Items</Text>
          </View>
          <View style={S.statBox}>
            <Text style={{ ...S.statNum, color: "#374151" }}>{advisory.recommendations.length}</Text>
            <Text style={S.statLabel}>Total Recommendations</Text>
          </View>
        </View>

        {/* Recommendations by phase */}
        {PHASES.map((phase) => {
          const recs = byPhase[phase];
          if (!recs?.length) return null;
          return (
            <View key={phase}>
              <Text style={S.sectionHdr}>{phase}</Text>
              {recs.map((rec, i) => (
                <View key={i} style={{ ...S.recCard, borderLeftColor: PRI_COLORS[rec.priority] ?? "#6b7280" }}>
                  <Text style={S.recText}>[{rec.priority}]  {rec.recommendation}</Text>
                  <Text style={S.basisText}>Basis: {rec.basis}</Text>
                  <Text style={S.confText}>Confidence: {rec.confidence}</Text>
                </View>
              ))}
            </View>
          );
        })}

        {/* Footer */}
        <Text style={S.footer}>
          MA-XAI Framework — Multi-Agent Explainable AI for Agricultural Advisory · Generated by Agent 5
        </Text>
      </Page>
    </Document>
  );
}

export async function downloadAdvisoryPDF(advisory: AdvisoryResult, farm: Record<string, unknown>) {
  const doc = <AdvisoryDocument advisory={advisory} farm={farm} />;
  const blob = await pdf(doc).toBlob();
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `MA-XAI_Advisory_${advisory.farm_label.replace(/\s+/g, "_")}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
